import './globals.css'
import { Inter, Open_Sans, Almarai } from 'next/font/google'
import localfont from 'next/font/local'

const inter = Inter({ subsets: ['latin'] })

const openSans = Open_Sans({ subsets: ['latin'] })

import 'swiper/css'
import 'swiper/css/navigation'
import 'swiper/css/pagination'
import 'swiper/css/scrollbar'
import { AnimatePresence } from 'framer-motion'
import { getDictionary } from '@/getDictionary'

export const metadata = {
  title: 'Department of Municipalities Affairs - Home',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, params }) {
  // console.log(params, 'params')
  // const lang2 = await getDictionary(params.lang)
  // console.log(lang2)

  // const { lang, setLang } = useLang()

  // setLang(params.lang === 'en' ? 'ar' : 'en') // Toggle between 'en' and 'fr'
  return (
    <html lang={params.lang}>
      {/* <body className={inter.className}>{children}</body> */}
      <body className={inter.className}>{children}</body>
    </html>
  )
}
